version: '3.8'

services:
  app:
    build: .
    container_name: portfolio-dev
    ports:
      - "3000:8080" # Map host 3000 to container 8080 (Vite dev server)
    volumes:
      - .:/app # Mount current directory for live reload
      - /app/node_modules # Prevents overwriting node_modules in container
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - .env # Loads environment variables if .env exists
    command: ["npm", "run", "dev"] 