services:
  app:
    build: .
    container_name: portfolio-dev
    ports:
      - "3000:8080" # Map host 3000 to container 8080 (Vite dev server)
    volumes:
      - .:/app          # live-reload your code
      - /app/node_modules   # ← keep deps from the image
    environment:
      - NODE_ENV=development
      - PORT=8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}   # <─ will read from your host env
    command: ["npm", "run", "dev"] 